### PR TITLE
Benchmarks in C++

### LINKED ISSUE #241: Missing benchmarks
No benchmarks are written for the datastreams.

### PR DESCRIPTION
**Pull request by ehpor**
Description
===

Add benchmarks for datastream latency (between submitting and receiving), datastream submitting itself (including copy) and timestamping. All benchmarks written in C++ to benchmark the internal speed and not the wrapper to Python.

- [x] Testing on MacOS.
- [x] Testing on Windows.

Fixes https://github.com/spacetelescope/catkit2/issues/241

MacOS benchmarks
===
Performed on Macbook Pro 16" M2 Max (12 cores, 64GB memory)

Submitting
---
```
With copying data:
1x1: 88.4 ns per submit
2x2: 88.5 ns per submit
4x4: 87.5 ns per submit
8x8: 84.5 ns per submit
16x16: 135.3 ns per submit
32x32: 303.7 ns per submit
64x64: 685.5 ns per submit
128x128: 2257 ns per submit
256x256: 8506.1 ns per submit
512x512: 34081.5 ns per submit
1024x1024: 165554 ns per submit
2048x2048: 611174 ns per submit

Without copying data:
1x1: 44.9 ns per submit
2x2: 47 ns per submit
4x4: 48.9 ns per submit
8x8: 48.5 ns per submit
16x16: 48.8 ns per submit
32x32: 52.4 ns per submit
64x64: 50.6 ns per submit
128x128: 51.7 ns per submit
256x256: 49.5 ns per submit
512x512: 50.2 ns per submit
1024x1024: 54.2 ns per submit
2048x2048: 51 ns per submit
```

Latency
---
image

Timestamping
---
```
15.1287 ns per timestamp
```

Windows benchmarks
===
Performed on hicat-deux: 

Submitting
---
```
With copying data:
1x1: 93.87 ns per submit
2x2: 95.07 ns per submit
4x4: 95.32 ns per submit
8x8: 104.26 ns per submit
16x16: 122.25 ns per submit
32x32: 214.08 ns per submit
64x64: 1566.98 ns per submit
128x128: 5815.06 ns per submit
256x256: 25002 ns per submit
512x512: 310941 ns per submit
1024x1024: 1.18724e+06 ns per submit
2048x2048: 6.40234e+06 ns per submit
Without copying data:
1x1: 127.61 ns per submit
2x2: 90.66 ns per submit
4x4: 91.51 ns per submit
8x8: 92.12 ns per submit
16x16: 90.98 ns per submit
32x32: 91.34 ns per submit
64x64: 91.23 ns per submit
128x128: 90.88 ns per submit
256x256: 91.25 ns per submit
512x512: 90.91 ns per submit
1024x1024: 122.83 ns per submit
2048x2048: 91.16 ns per submit
```

Latency
---
Screenshot 2024-08-22 175353

Timestamping
---
```
23.8282 ns per timestamp
```

### CODE REVIEW

**Comment by ehpor** [comment]
Since this changes CI from Ubuntu 20.04 to Ubuntu 22.04, we need to change the required checks on Github too. But I'll do that after approval of this PR.

**Comment by ehpor** [comment]
Also, important side note. This PR changes Python to version 3.7.16 from 3.7.6. This is a binary compatible version. But we should be certain about compatibility.

**Review by ivalaginja — APPROVED** [review]
Looks very good to me, and very interesting to see the results now without going through Python.
Stupid question from someone who never touches C++: How can I run these tests? Just compile and run?

**Comment by ehpor** [comment]
@ivalaginja The benchmarks are compiled alongside the Python library when you run `python setup.py develop`. You can run them from the `build/bin` folder.

@RemiSoummer Waiting for you to approve the Python 3.7.6 to Python 3.7.16` change.

**Comment by ivalaginja** [comment]
> @ivalaginja The benchmarks are compiled alongside the Python library when you run `python setup.py develop`. You can run them from the `build/bin` folder.

@ehpor Should this be contained in the documentation somewhere or is this common knowledge? I suspect it's the latter, might just not be true for an audience like me 😬

**Comment by ehpor** [comment]
Checked with a full install on HiCAT that this is compatible. I did not install the BMC DMs nor the FLIR camera.

**Pull request merged**
