### PR TITLE
Add stages models to the thorlabs kinesis motors service

### LINKED ISSUE #217: Add stages Z806 and Z812 to accepted list of stages in Thorlabs cube motor service

### PR DESCRIPTION
**Pull request by erinpougheon**
Add the Z806 and Z812 to the list of accepted stages for the Thorlabs Kinesis motors.

### CODE REVIEW

**Comment by erinpougheon** [comment]
The 2 stages we need are added to the list, and I erased the unecessary comments you told me !
This is ready for review.

**Comment by ivalaginja** [comment]
@erinpougheon have you checked that the new stages use the same gear step per revolution, gear box ratio and pitch like the ones that are already in the list? I believe @a-sevin had checked their manuals to confirm the numbers.

**Comment by erinpougheon** [comment]
> @erinpougheon have you checked that the new stages use the same gear step per revolution, gear box ratio and pitch like the ones that are already in the list? I believe @a-sevin had checked their manuals to confirm the numbers.

I checked right now in all the manuals to be sure, and yes they all have the same gear step per revolution, gear box ratio and pitch!

**Review by ivalaginja — APPROVED** [review]
LGTM

**Pull request merged**
